/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.coordenador;

import controller.coordenador.rank.RankAlunoMaisParticipativoController;
import controller.coordenador.rank.RankDisciplinaComMaiorNumeroAtendimentoController;
import controller.coordenador.rank.RankDisciplinaMaisFrequentadaController;
import controller.coordenador.rank.RankMonitorQueMaisDisponibilizouAtendimentoController;
import controller.main.LoginController;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import view.aluno.*;
import javax.swing.SwingConstants;
import model.bean.AlunoBean;
import view.coordenador.rank.RankAlunoMaisParticipativoView;
import view.coordenador.rank.RankDisciplinaComMaiorNumeroAtendimentoView;
import view.coordenador.rank.RankDisciplinaMaisFrequentadaView;
import view.coordenador.rank.RankMonitorQueMaisDisponibilizouAtendimentoView;
import view.main.LoginView;

/**
 *
 * @author Aluno
 */
public class MenuCoordenadorView extends javax.swing.JFrame {

    /**
     * Creates new form MenuMonitor
     */
    public MenuCoordenadorView() {
        initComponents();
        btnReserva.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnReserva.setHorizontalTextPosition(SwingConstants.CENTER);
        btnTeste1.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnTeste1.setHorizontalTextPosition(SwingConstants.CENTER);
        btnTeste2.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnTeste2.setHorizontalTextPosition(SwingConstants.CENTER);
        btnTeste3.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnTeste3.setHorizontalTextPosition(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnTeste2 = new javax.swing.JButton();
        btnTeste1 = new javax.swing.JButton();
        btnTeste3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel18.setBackground(new java.awt.Color(73, 103, 149));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("MONITOREASY");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnReserva.setBackground(new java.awt.Color(8, 35, 87));
        btnReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/booking (2).png"))); // NOI18N
        btnReserva.setText("DISPONIBILIZAR HORÁRIO");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("MENU COORDENADOR");

        btnTeste2.setBackground(new java.awt.Color(8, 35, 87));
        btnTeste2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTeste2.setForeground(new java.awt.Color(255, 255, 255));
        btnTeste2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/education.png"))); // NOI18N
        btnTeste2.setText("MONITORES");
        btnTeste2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeste2ActionPerformed(evt);
            }
        });

        btnTeste1.setBackground(new java.awt.Color(8, 35, 87));
        btnTeste1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTeste1.setForeground(new java.awt.Color(255, 255, 255));
        btnTeste1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/intellectual.png"))); // NOI18N
        btnTeste1.setText("TESTE 01");
        btnTeste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeste1ActionPerformed(evt);
            }
        });

        btnTeste3.setBackground(new java.awt.Color(8, 35, 87));
        btnTeste3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTeste3.setForeground(new java.awt.Color(255, 255, 255));
        btnTeste3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/pros-and-cons.png"))); // NOI18N
        btnTeste3.setText("TESTE 03");
        btnTeste3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeste3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Conta");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem3.setText("Aluno mais participativo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Disciplina com mais atendimentos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Disciplina mais frequentada");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Monitor que mais disponibilizou");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeste2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTeste1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(btnTeste3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserva)
                    .addComponent(btnTeste1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeste2)
                    .addComponent(btnTeste3))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnTeste2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeste2ActionPerformed

    private void btnTeste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeste1ActionPerformed

    private void btnTeste3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeste3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AlunoBean.mat = 0;
        new LoginController(new LoginView());
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new RankAlunoMaisParticipativoController(new RankAlunoMaisParticipativoView());
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new RankDisciplinaComMaiorNumeroAtendimentoController(new RankDisciplinaComMaiorNumeroAtendimentoView());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new RankDisciplinaMaisFrequentadaController(new RankDisciplinaMaisFrequentadaView());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new RankMonitorQueMaisDisponibilizouAtendimentoController(new RankMonitorQueMaisDisponibilizouAtendimentoView());
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    public void addBtnOption1Listener(ActionListener listener){
        this.btnReserva.addActionListener(listener);
    }
    public void addBtnOption2Listener(ActionListener listener){
        this.btnTeste1.addActionListener(listener);
    }
    public void addBtnOption3Listener(ActionListener listener){
        this.btnTeste2.addActionListener(listener);
    }
    public void addBtnOption4Listener(ActionListener listener){
        this.btnTeste3.addActionListener(listener);
    }
    public void showMsg(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
    public void closeView(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCoordenadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCoordenadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCoordenadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCoordenadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCoordenadorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserva;
    private javax.swing.JButton btnTeste1;
    private javax.swing.JButton btnTeste2;
    private javax.swing.JButton btnTeste3;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel18;
    // End of variables declaration//GEN-END:variables
}
