/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.aluno;

import controller.aluno.MenuAlunoController;
import controller.coordenador.MenuCoordenadorController;
import controller.main.LoginController;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.MouseListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.MenuListener;
import javax.swing.event.PopupMenuListener;
import model.bean.AlunoBean;
import view.coordenador.MenuCoordenadorView;
import view.main.LoginView;

/**
 *
 * @author Aluno
 */
public class ReservarAtendimentoView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroNaMonitoriaView
     */
    public ReservarAtendimentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDisciplina = new javax.swing.JComboBox<>();
        cmbMonitor = new javax.swing.JComboBox<>();
        cmbLocal = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblDisc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        cmbHorario = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        lblVoltar15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        dpData = new org.jdesktop.swingx.JXDatePicker();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Disciplinas--" }));
        cmbDisciplina.setPreferredSize(new java.awt.Dimension(90, 20));

        cmbMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Monitores--" }));
        cmbMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonitorActionPerformed(evt);
            }
        });

        cmbLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Locais--" }));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        lblDisc.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        lblEmail.setText("jLabel3");

        lblPeriodo.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblPeriodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail)
                .addGap(18, 18, 18)
                .addComponent(lblPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Horários--" }));

        jPanel18.setBackground(new java.awt.Color(73, 103, 149));

        lblVoltar15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVoltar15.setForeground(new java.awt.Color(255, 255, 255));
        lblVoltar15.setText("Voltar");
        lblVoltar15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltar15MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CADASTRO NA MONITORIA");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblVoltar15)
                .addGap(297, 297, 297)
                .addComponent(jLabel20)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblVoltar15))
                .addGap(19, 19, 19))
        );

        btnReservar.setBackground(new java.awt.Color(8, 35, 87));
        btnReservar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("CONFIRMAR");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLista.setBackground(new java.awt.Color(8, 35, 87));
        btnLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("MEUS ATENDIMENTOS");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        jMenu1.setText("Conta");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbDisciplina, 0, 270, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMonitor, javax.swing.GroupLayout.Alignment.LEADING, 0, 270, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dpData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbHorario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReservar))
                    .addComponent(cmbLocal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(dpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cmbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReservar)
                            .addComponent(btnLista)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMonitorActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaActionPerformed

    private void lblVoltar15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltar15MouseClicked
        new MenuAlunoController(new MenuAlunoView());
        this.dispose();
    }//GEN-LAST:event_lblVoltar15MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AlunoBean.mat = 0;
        new LoginController(new LoginView());
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public Calendar getDpData(){
        return this.dpData.getMonthView().getCalendar();        
    }
    public Date getDpDataDate(){
        return dpData.getDate();
    }
    public void setDpDataLowerBound(Date calendar){
        dpData.getMonthView().setLowerBound(calendar);
    }
    // recebe do controle a data limite máxima
    public void setDpDataUpperBound(Date calendar){
        dpData.getMonthView().setUpperBound(calendar);
    }
    
    public void setDpDataFormats(String format){
        dpData.setFormats(format);
    }
    public void setdpDataFlaggedDates(Date calendar[]){
        dpData.getMonthView().setFlaggedDates(calendar);
    }
    public boolean dataIsEmpty(){
        if(dpData.getDate() == null){
            return true;
        }
        return false;
    }
    public void setDpDataColor(Color color){
        this.dpData.getMonthView().setFlaggedDayForeground(color);
    }
    public void setLblDiscVisible(Boolean ok){
        lblDisc.setVisible(ok);
    }
    public void setLblEmailVisible(Boolean ok){
        lblEmail.setVisible(ok);
    }
    public void setLblPeriodoVisible(Boolean ok){
        lblPeriodo.setVisible(ok);
    }
    public void setLblDiscText(String text){
        lblDisc.setText(text);
    }
    public void setLblEmailText(String text){
        lblEmail.setText(text);
    }
    public void setLblPeriodoText(String text){
        lblPeriodo.setText(text);
    }
    public void addItemComboBox(String disciplina){
        cmbDisciplina.addItem(disciplina);
    }
    public void addItemComboBoxMonitor(String monitor){
        cmbMonitor.addItem(monitor);
    }
    public void addItemComboBoxLocal(String local){
        cmbLocal.addItem(local);
    }
    public void addItemComboBoxHorario(String horario){
        cmbHorario.addItem(horario);
    }
    public void clearComboBoxMonitor(){
        cmbMonitor.removeAllItems();
    }
    public void clearComboBoxLocal(){
        cmbLocal.removeAllItems();
    }
    public void clearComboBoxHorario(){
        cmbHorario.removeAllItems();
    }
    public void showMsg(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
    public void setEnabledCmbMonitor(boolean ok){
        cmbMonitor.setEnabled(ok);
    }
    public void setEnabledCmbDisciplina(boolean ok){
        cmbDisciplina.setEnabled(ok);
    }
    public void setEnabledCmbLocal(boolean ok){
        cmbLocal.setEnabled(ok);
    }
    public void setEnabledCmbHora(boolean ok){
        cmbHorario.setEnabled(ok);
    }
    public void setEnabledDpData(boolean ok){
        dpData.setEnabled(ok);
    }
    public void setDisabledEditorDpData(){
        dpData.getEditor().setEditable(false);
    }
    public void addCmbDisciplinaListener(ActionListener listener){
        this.cmbDisciplina.addActionListener(listener);
    }
    public void addCmbMonitorListener(ActionListener listener){
        this.cmbMonitor.addActionListener(listener);
    }
    public void addCmbLocalListener(ActionListener listener){
        this.cmbLocal.addActionListener(listener);
    }
    public void addDpDataListener(ActionListener listener){
        this.dpData.addActionListener(listener);
    }
    public void addBtnListaListener(ActionListener listener){
        this.btnLista.addActionListener(listener);
    }
    public void addBtnReservarListener(ActionListener listener){
        this.btnReservar.addActionListener(listener);
    }
    public int returnIndexCmbDisciplina(){
        return cmbDisciplina.getSelectedIndex();
    }
    public int returnIndexCmbMonitor(){
        return cmbMonitor.getSelectedIndex();
    }
    public int returnIndexCmbLocal(){
        return cmbLocal.getSelectedIndex();
    }
    public int returnIndexCmbHora(){
        return cmbHorario.getSelectedIndex();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservarAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservarAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservarAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservarAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservarAtendimentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cmbDisciplina;
    private javax.swing.JComboBox<String> cmbHorario;
    private javax.swing.JComboBox<String> cmbLocal;
    private javax.swing.JComboBox<String> cmbMonitor;
    private org.jdesktop.swingx.JXDatePicker dpData;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblVoltar15;
    // End of variables declaration//GEN-END:variables
}
